version: "3"

services:
  ##########################################
  # Overrides for oada-core services:
  ##########################################

  # Add ourselves to admin container:
  admin:
    volumes:
      - ./services-available/oada-backups:/code/oada-backups
      - oada_backups_volume:/oada-backups


  ###############################################
  # This service's definition:
  ###############################################
  oada-backups:
    build:
      context: ./services-available/oada-backups
    container_name: oada-backups
    restart: always
    networks:
      - arango_net
    volumes:
      - ./services-available/oada-backups/daily:/etc/periodic/daily
      - ./services-available/oada-backups:/code/oada-backups
      - oada_backups_volume:/oada-backups
    command: crond -f -d 8

volumes:
  oada_backups_volume:
